export interface SystemCategorySeed {
  id: string;
  code: string;
  name: string;
  parentId: string | null;
  aliases?: string[];
  sortOrder: number;
}

export const SYSTEM_PRODUCT_CATEGORIES: SystemCategorySeed[] = [
  {
    id: "syscat_shoes_apparel",
    code: "SHOES_APPAREL",
    name: "鞋服",
    parentId: null,
    aliases: ["服饰"],
    sortOrder: 10,
  },
  {
    id: "syscat_footwear",
    code: "FOOTWEAR",
    name: "鞋类",
    parentId: "syscat_shoes_apparel",
    aliases: ["鞋子"],
    sortOrder: 11,
  },
  {
    id: "syscat_sneakers",
    code: "SNEAKERS",
    name: "运动鞋",
    parentId: "syscat_footwear",
    aliases: ["球鞋", "休闲运动鞋"],
    sortOrder: 12,
  },
  {
    id: "syscat_casual_shoes",
    code: "CASUAL_SHOES",
    name: "休闲鞋",
    parentId: "syscat_footwear",
    sortOrder: 13,
  },
  {
    id: "syscat_boots",
    code: "BOOTS",
    name: "靴类",
    parentId: "syscat_footwear",
    aliases: ["靴子"],
    sortOrder: 14,
  },
  {
    id: "syscat_apparel",
    code: "APPAREL",
    name: "服装",
    parentId: "syscat_shoes_apparel",
    aliases: ["服饰", "衣服"],
    sortOrder: 15,
  },
  {
    id: "syscat_tops",
    code: "TOPS",
    name: "上装",
    parentId: "syscat_apparel",
    sortOrder: 16,
  },
  {
    id: "syscat_bottoms",
    code: "BOTTOMS",
    name: "下装",
    parentId: "syscat_apparel",
    sortOrder: 17,
  },
  {
    id: "syscat_outerwear",
    code: "OUTERWEAR",
    name: "外套",
    parentId: "syscat_apparel",
    sortOrder: 18,
  },
  {
    id: "syscat_fashion_accessories",
    code: "FASHION_ACCESSORIES",
    name: "服饰配件",
    parentId: "syscat_shoes_apparel",
    aliases: ["帽子", "围巾", "皮带"],
    sortOrder: 19,
  },
  {
    id: "syscat_jewelry",
    code: "JEWELRY_ACCESSORIES",
    name: "首饰配件",
    parentId: null,
    aliases: ["饰品", "珠宝"],
    sortOrder: 20,
  },
  {
    id: "syscat_necklaces",
    code: "NECKLACES",
    name: "项链",
    parentId: "syscat_jewelry",
    sortOrder: 21,
  },
  {
    id: "syscat_rings",
    code: "RINGS",
    name: "戒指",
    parentId: "syscat_jewelry",
    sortOrder: 22,
  },
  {
    id: "syscat_earrings",
    code: "EARRINGS",
    name: "耳饰",
    parentId: "syscat_jewelry",
    aliases: ["耳环", "耳钉"],
    sortOrder: 23,
  },
  {
    id: "syscat_bracelets",
    code: "BRACELETS",
    name: "手链与手镯",
    parentId: "syscat_jewelry",
    sortOrder: 24,
  },
  {
    id: "syscat_watches",
    code: "WATCHES",
    name: "腕表",
    parentId: "syscat_jewelry",
    aliases: ["手表"],
    sortOrder: 25,
  },
  {
    id: "syscat_toys_collectibles",
    code: "TOYS_COLLECTIBLES",
    name: "玩具与收藏",
    parentId: null,
    aliases: ["玩具", "收藏品"],
    sortOrder: 30,
  },
  {
    id: "syscat_designer_toys",
    code: "DESIGNER_TOYS",
    name: "潮玩",
    parentId: "syscat_toys_collectibles",
    sortOrder: 31,
  },
  {
    id: "syscat_blind_boxes",
    code: "BLIND_BOXES",
    name: "盲盒",
    parentId: "syscat_toys_collectibles",
    sortOrder: 32,
  },
  {
    id: "syscat_figures",
    code: "FIGURES",
    name: "手办与模型",
    parentId: "syscat_toys_collectibles",
    aliases: ["手办", "模型"],
    sortOrder: 33,
  },
  {
    id: "syscat_trading_cards",
    code: "TRADING_CARDS",
    name: "卡牌",
    parentId: "syscat_toys_collectibles",
    sortOrder: 34,
  },
  {
    id: "syscat_plush",
    code: "PLUSH_TOYS",
    name: "毛绒玩具",
    parentId: "syscat_toys_collectibles",
    sortOrder: 35,
  },
  {
    id: "syscat_bags",
    code: "BAGS_LUGGAGE",
    name: "箱包",
    parentId: null,
    aliases: ["包袋", "中古包"],
    sortOrder: 40,
  },
  {
    id: "syscat_handbags",
    code: "HANDBAGS",
    name: "手提包与肩背包",
    parentId: "syscat_bags",
    sortOrder: 41,
  },
  {
    id: "syscat_backpacks",
    code: "BACKPACKS",
    name: "双肩包",
    parentId: "syscat_bags",
    sortOrder: 42,
  },
  {
    id: "syscat_luggage",
    code: "LUGGAGE",
    name: "旅行箱包",
    parentId: "syscat_bags",
    sortOrder: 43,
  },
  {
    id: "syscat_daily_life",
    code: "DAILY_LIFE",
    name: "生活用品",
    parentId: null,
    aliases: ["日用", "杂货"],
    sortOrder: 50,
  },
  {
    id: "syscat_home_daily",
    code: "HOME_DAILY",
    name: "居家日用",
    parentId: "syscat_daily_life",
    aliases: ["家居"],
    sortOrder: 51,
  },
  {
    id: "syscat_kitchen",
    code: "KITCHEN_DINING",
    name: "厨房与餐具",
    parentId: "syscat_daily_life",
    sortOrder: 52,
  },
  {
    id: "syscat_storage",
    code: "HOME_STORAGE",
    name: "收纳整理",
    parentId: "syscat_daily_life",
    sortOrder: 53,
  },
  {
    id: "syscat_cleaning",
    code: "CLEANING_SUPPLIES",
    name: "清洁用品",
    parentId: "syscat_daily_life",
    sortOrder: 54,
  },
  {
    id: "syscat_stationery",
    code: "STATIONERY",
    name: "文具",
    parentId: "syscat_daily_life",
    sortOrder: 55,
  },
  {
    id: "syscat_digital",
    code: "DIGITAL_ELECTRONICS",
    name: "数码家电",
    parentId: null,
    aliases: ["数码", "电子产品"],
    sortOrder: 60,
  },
  {
    id: "syscat_cameras",
    code: "CAMERAS",
    name: "相机与摄影",
    parentId: "syscat_digital",
    aliases: ["相机", "摄影器材"],
    sortOrder: 61,
  },
  {
    id: "syscat_phones",
    code: "PHONES_ACCESSORIES",
    name: "手机与配件",
    parentId: "syscat_digital",
    sortOrder: 62,
  },
  {
    id: "syscat_computers",
    code: "COMPUTERS_ACCESSORIES",
    name: "电脑与配件",
    parentId: "syscat_digital",
    sortOrder: 63,
  },
  {
    id: "syscat_gaming",
    code: "GAMING",
    name: "游戏设备",
    parentId: "syscat_digital",
    aliases: ["游戏"],
    sortOrder: 64,
  },
  {
    id: "syscat_beauty",
    code: "BEAUTY_PERSONAL_CARE",
    name: "美妆个护",
    parentId: null,
    aliases: ["美妆", "个护"],
    sortOrder: 70,
  },
  {
    id: "syscat_sports",
    code: "SPORTS_OUTDOORS",
    name: "运动户外",
    parentId: null,
    aliases: ["户外"],
    sortOrder: 80,
  },
  {
    id: "syscat_mother_baby",
    code: "MOTHER_BABY",
    name: "母婴用品",
    parentId: null,
    aliases: ["母婴"],
    sortOrder: 90,
  },
  {
    id: "syscat_other",
    code: "OTHER",
    name: "其他",
    parentId: null,
    sortOrder: 999,
  },
];

export const SYSTEM_CATEGORY_ID_BY_LEGACY_NAME: Record<string, string> = {
  鞋服: "syscat_shoes_apparel",
  鞋类: "syscat_footwear",
  球鞋: "syscat_sneakers",
  运动鞋: "syscat_sneakers",
  服装: "syscat_apparel",
  服饰: "syscat_apparel",
  饰品: "syscat_jewelry",
  首饰: "syscat_jewelry",
  玩具: "syscat_toys_collectibles",
  潮玩: "syscat_designer_toys",
  盲盒: "syscat_blind_boxes",
  手办: "syscat_figures",
  卡牌: "syscat_trading_cards",
  中古包: "syscat_bags",
  生活用品: "syscat_daily_life",
  家居: "syscat_home_daily",
  杂货: "syscat_daily_life",
  数码: "syscat_digital",
  相机: "syscat_cameras",
  游戏: "syscat_gaming",
};
